var
GPSLocation = 'Amsterdam centraal',
CurrentWeather = 'cloudy',
CurrentTemperature = 18,
Wind = 10,
PrecipitationChance = 10,
Humidity = 70,
Maintenance = true,
firstName = "Melissa",
lastName = "Vriend",
Age = 20,
DayOfBirth = 10,
MonthOfBirth = 04,
YearOfBirth = 2000,
Student = false,
StudentOV = false;
